### ISSUE TITLE
异步PublishAsync触发的Handler中无法再次PublishAsync

### ISSUE THREAD

**Issue by Memoyu** [masastack/MASA.Framework#425]
**模块：** [Dispatcher.Event](https://github.com/masastack/MASA.Framework/tree/main/src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events)</br>
**场景：** 在业务处理中，存在某些耗时操作，当请求到达后，直接触发处理，然后返回请求端成功，并且在耗时操作中涉及事件触发；</br>
**Code：** 
``` C#
// controller
app.MapGet("/publish", async ([FromServices] IEventBus eventBus) =>
{
    return eventBus.PublishAsync(new Event1());
});

// handler
// 存在耗时操作，并且会继续PublishAsync
[EventHandler]
public async Task Handler(Event1 e1)
{
    await Task.Delay(4000);
    await _eventBus.PublishAsync(new Event2());
}
```
**异常：** 
``` C#
fail: Masa.Contrib.Dispatcher.Events.DefaultExceptionStrategyProvider[0]
      ----- Error Publishing event Event1 { }: after 0th executions and we will stop retrying. message id: d9d4fe5d-4ef6-4155-b036-edd701668edd -----
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'IServiceProvider'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Masa.Contrib.Dispatcher.Events.EventBus.PublishAsync[TEvent](TEvent event)
         at Masa.Dispatcher.Test.Event1Handler.Handler(Event1 e1) in D:\Workspace\Test\Masa.Dispatcher.Test\Masa.Dispatcher.Test\Event1Handler.cs:line 21
         at Masa.Contrib.Dispatcher.Events.EventHandlerAttribute.ExcuteAction[TEvent](IServiceProvider serviceProvider, TEvent event)
         at Masa.Contrib.Dispatcher.Events.Internal.Dispatch.DispatcherBase.<>c__DisplayClass7_0`1.<<ExecuteEventHandlerAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Masa.Contrib.Dispatcher.Events.Strategies.ExecutionStrategy.ExecuteAsync[TEvent](StrategyOptions strategyOptions, TEvent event, Func`2 func, Func`4 cancel) 
```
**期望：** 在PublishAsync我可以选择等待处理完成，也可以在触发事件后让事件处理在后台异步执行；

**Comment by doddgu** [comment]
你有两种办法解决。
1. controller中await
2. controller中起一个新的task，在task中创建新的scope横跨task的运行生命周期，在scope中重新获取eventbus。

当然后续我们也会对这个功能进行优化，我们可能使用类似后台服务的方式来降低代码编写复杂度，但这应该在2.0中。

**Comment by Memoyu** [comment]
@doddgu 是的，以上的方式确实可以，就是很不优雅，😏主要是希望官方支持；
不过在我们实际业务中，单纯进行如上操作还是出现了问题，最终在@zhenlei520 大佬的协助下，才解决了问题，但又多了一行更不优雅的代码，就是在注册完成后将IServiceProvider暂存：
``` C#
 MasaApp.Build(app.ApplicationServices);
```

**Comment by doddgu** [comment]
我们将会在1.0提供支持

**Comment by Memoyu** [comment]
🙌辛苦了

**Comment by zhenlei520** [comment]
Resolved at [#480](https://github.com/masastack/MASA.Framework/pull/480)
