### ISSUE TITLE
cli 创建 masafx project 报错

### ISSUE THREAD

**Issue by hangyejiadao** [masastack/MASA.Framework#545]
### Description

 
![44a2cfcb4ad322eccedce09fe2047e9](https://user-images.githubusercontent.com/16451639/230773675-153ec985-c2d3-4973-a857-f9801392c543.png)

### .NET version

7.0.1

### MASA Framework version

Masa.Template::0.6.4000。

**Comment by zhenlei520** [comment]
能否提供更详细的信息？按照提供信息并未成功复现问题

```shell
E:\Temp>dotnet --list-sdks
6.0.406 [C:\Program Files\dotnet\sdk]
7.0.201 [C:\Program Files\dotnet\sdk]

E:\Temp>dotnet new uninstall
当前已安装项:
   Masa.Template
      版本: 0.6.4000
      详细信息:
         Author: Masa
         NuGetSource: https://api.nuget.org/v3/index.json
      模板:
         MASA Framework Project (masafx) C#
         MASA Blazor Website (masabw) C#
         MASA Blazor App (masab) C#
         MASA Blazor Pro Web (masabp) C#
      卸载命令:
         dotnet new uninstall Masa.Template


E:\Temp>dotnet new masafx --name mfDemo
已成功创建模板“MASA Framework Project”。

正在处理创建后操作...
正在还原 E:\Temp\mfDemo\mfDemo.app.sln:
  正在确定要还原的项目…
  已还原 E:\Temp\mfDemo\src\Contracts\mfDemo.Contracts.Order\mfDemo.Contracts.Order.csproj (用时 52 ms)。
  已还原 E:\Temp\mfDemo\src\ApiGateways\Caller\mfDemo.Caller\mfDemo.Caller.csproj (用时 144 ms)。
  已还原 E:\Temp\mfDemo\src\Services\mfDemo.Service\mfDemo.Service.Order.csproj (用时 145 ms)。
  已还原 E:\Temp\mfDemo\src\Web\mfDemo.Admin\mfDemo.Admin.csproj (用时 247 ms)。
已成功还原
```

**Comment by hangyejiadao** [comment]
报错信息:
An item with the same key has already been added. Key: -p:A
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CliTemplateInfo template, Boolean validateDefaultLanguage)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IEnumerable`1 templatesToReparse, Boolean& languageOptionSpecified)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.GetTemplateCommand(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

有关退出代码的详细信息，请参阅 https://aka.ms/templating-exit-codes#70

**Comment by zhenlei520** [comment]
可能这个属于`.NET 7.0.1`的错误，我尝试使用全新的环境安装了`.NET 7.0`，但仍未能复现错误

```shell
root@sskj-007:/home/download# dotnet --list-sdks
7.0.202 [/root/.dotnet/sdk]

root@sskj-007:/home/download# dotnet new uninstall
Currently installed items:
   Masa.Template
      Version: 0.6.4000
      Details:
         Author: Masa
         NuGetSource: https://api.nuget.org/v3/index.json
      Templates:
         MASA Framework Project (masafx) C#
         MASA Blazor Website (masabw) C#
         MASA Blazor App (masab) C#
         MASA Blazor Pro Web (masabp) C#
      Uninstall Command:
         dotnet new uninstall Masa.Template

root@sskj-007:/home/download# dotnet new masafx -n Masa.EShop
The template "MASA Framework Project" was created successfully.

Processing post-creation actions...
Restoring /home/download/Masa.EShop/Masa.EShop.app.sln:
  Determining projects to restore...
  Restored /home/download/Masa.EShop/src/Contracts/Masa.EShop.Contracts.Order/Masa.EShop.Contracts.Order.csproj (in 4.07 sec).
  Restored /home/download/Masa.EShop/src/ApiGateways/Caller/Masa.EShop.Caller/Masa.EShop.Caller.csproj (in 4.1 sec).
  Restored /home/download/Masa.EShop/src/Services/Masa.EShop.Service/Masa.EShop.Service.Order.csproj (in 4.46 sec).
  Restored /home/download/Masa.EShop/src/Web/Masa.EShop.Admin/Masa.EShop.Admin.csproj (in 5.93 sec).
Restore succeeded.
```

**Comment by zhenlei520** [comment]
后续如果有更多关于此问题的细节，欢迎继续提问
